### ISSUE TITLE
Link to particular notebook

### ISSUE THREAD

**Issue by mrocklin** [binder-project/binder#18]
Is there a way to link to a particular notebook hosted on mybinder?

**Comment by freeman-lab** [comment]
Not yet but definitely possible! @andrewosh and I just sketched it out. Mind opening an issue on the web app (https://github.com/binder-project/binder-web), it'll happen over there.

And the behavior we're imaging is something like this for linking to a notebook at the top level

```
mybinder.org/repo/user-name/repo-name/notebook-name.ipynb
```

this for linking to a sub-folder (presumably one with many notebooks)

```
mybinder.org/repo/user-name/repo-name/folder-name/
```

and this for a notebook in a sub-folder

```
mybinder.org/repo/user-name/repo-name/folder-name/notebook-name.ipynb
```

If that's not what you had in mind, definitely let us know what would be most intuitive!

**Comment by mrocklin** [comment]
This is definitely what I had in mind
