### ISSUE TITLE
python3.4 vs python3.3

### ISSUE THREAD

**Issue by hainm** [binder-project/binder#23]
Hi,

currently binder only support python3.3 and python2.7. What do you think about switching 3.3 to 3.4?

IMO, 3.4 is more 'mainstream'  and newer. 
(This is actually from my experience building my Python package with conda. It's likely that python3.3 is not as well supported as 3.4 with conda).

**Comment by minrk** [comment]
3.4 is old-news, 3.5 is current stable!

But you are right - in my experience, 3.4 is typically better supported by just about everything than 3.3, though there isn't much that works on 3.4 that doesn't on 3.3. My guess is the decision was based on what Python shipped with the base distro prior to adopting conda, but that could be wrong.

**Comment by freeman-lab** [comment]
Thanks for catching @hainm and for the comments @minrk ! Was a totally arbitrary choice in our base image, we're changing it to 3.5 right now, want that sweet new `@` :sparkles:  

cc @andrewosh

**Comment by ellisonbg** [comment]
I don't know if this is relevant, but the anaconda packages aren't out for
3.5 (even though conda has it).

On Tue, Sep 22, 2015 at 8:53 AM, Jeremy Freeman notifications@github.com
wrote:

> Thanks for catching @hainm https://github.com/hainm and for the
> comments @minrk https://github.com/minrk ! Was a totally arbitrary
> choice in our base image, we're changing it to 3.5 right now, want that
> sweet new @ [image: :sparkles:]
> 
> cc @andrewosh https://github.com/andrewosh
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/binder-project/binder/issues/23#issuecomment-142331550
> .

## 

Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by minrk** [comment]
Might be premature for 3.5, sorry if I misled. Many conda packages are up for 3.5 (jupyter), but there are still important ones not yet out (e.g. matplotlib).

**Comment by andrewosh** [comment]
Python 3.4 is installed in the base image as of e85d1a1
