### ISSUE TITLE
Support setuptools (setup.py)

### ISSUE THREAD

**Issue by show0k** [binder-project/binder#25]
Hi,
I just see this great project but I was disappointed when I see it lacks setuptools support. 
I use jupyter notebooks as code examples for my libraries. As I assume that the user has installed my library all imports of my code in the notebook didn't take account of the path of this code...
I could modify my notebooks to make it work with binder, but I think it could be very convenient for many people too add simple "python setup.py install in your docker file.

**Comment by freeman-lab** [comment]
Thanks for your interest @show0k ! Using Binders as examples for your code is a great use case! Often we've done this with repos that are in PyPi, so hadn't run into this.

We could definitely look at adding support for a `setup.py`, what do you think @andrewosh ? The other option is to use `requirements.txt` and just list your requirements as packages to be installed from git. The syntax looks like `pip install git+git://...` read here for more:

https://pip.pypa.io/en/latest/reference/pip_install/#vcs-support

Maybe give that a try and let us know how it goes? One advantage of that approach is that it lets you combine a dependency on your own library with other libraries that might be used in your notebooks (but are not necessarily requirements of your library itself).

**Comment by nthiery** [comment]
I just stumbled on this issue after having created https://github.com/binder-project/binder-docs/issues/5.
A trick that worked for me is to put a trivial requirements.txt file containing:

    -e .

If this is confirmed as a proper way to go, I guess documenting this trick -- or any variant -- is good enough to close this issue.

**Comment by show0k** [comment]
Thanks !
I'm closing the issue.
