### ISSUE TITLE
Jupyer terminal?

### ISSUE THREAD

**Issue by roliveira** [binder-project/binder#26]
I don't see a lot of benefits from leaving the terminal interface from Jupyter exposed in `http://app.mybinder.org/###/terminals/1`. I can't think of any  immediate harm, but I'm sure someone else might!

**Comment by andrewosh** [comment]
Well, at the end of the day anyone can still run any shell command (either with `subprocess` or with the `!` operator in the notebook), so I don't think leaving it in creates any additional vulnerability. This shouldn't be a problem if you use one of the dependency files, where we ensure that you run as the `main` user. But if you write your own Dockerfile, then it can lead to problems, and we're trying to figure out the right way to solve this (see #15).

**Comment by roliveira** [comment]
Yes, you definitely right. The Dockerfile is critical, I will follow-up in #15.
