### ISSUE TITLE
Update the base image to Python 3.5

### ISSUE THREAD

**Issue by brettcannon** [binder-project/binder#38]
Python 3.5.0 is out and Anaconda 2.4.0 has it so it would be great to have the base image updated to use it.

**Comment by tiagoantao** [comment]
+1
Not only that, but also a way to specify that requirements.txt or environment.yml apply to Python 3 and not 2.
In practice I end up having to use Dockerfile for configuration.

**Comment by andrewosh** [comment]
Thanks for the feedback! The base image has been updated to use both Anaconda 4.0.0 and Python 3.5 in https://github.com/binder-project/binder/commit/29c4e3dbda94e80b1b22c82997e554a25cd187ff . 

@tiagoantao as of now, the dependencies in a `requirements.txt` file will be installed in both the Python 2.7 and the Python 3.x environments, and you can specify a language dependency in an `environment.yml` file (check out this example https://github.com/binder-project/example-conda-environment/blob/master/environment.yml ). Hopefully that should let you avoid writing a Dockerfile.

In the upcoming 1.0 release, we're going to let you choose from a larger variety of base images, and we'll  have much more thorough documentation!

**Comment by tiagoantao** [comment]
I tried with requirements.txt and it only loaded on 2.7. There might be a
bug in there.

With regards conda: thanks for the example - It should solve my problems.
