### ISSUE TITLE
Add support for conda environment.yml

### ISSUE THREAD

**Issue by freeman-lab** [binder-project/binder#6]
Along with the current support for `requirements.txt` (simple Python dependencies) and `Dockerfile`, we should probably add support for the `conda` `environment.yml` specification. This has come up in the Jupyter mailing list (https://groups.google.com/forum/#!topic/jupyter/7Q9G5LULc-I) as an appealing way to specify `conda` dependencies, as well as enable easier specification of optional kernels.

**Comment by rgbkrk** [comment]
:+1:

**Comment by andrewosh** [comment]
Support added in 83361eeb5ff88ac51edef060356a965268914118
