### ISSUE TITLE
Build delay due to usage of `ipython trust`

### ISSUE THREAD

**Issue by akhmerov** [binder-project/binder#66]
Looking at the build logs right now shows a bunch of messages:

```
[TerminalIPythonApp] WARNING | Subcommand `ipython trust` is deprecated and will be removed in future versions.

[TerminalIPythonApp] WARNING | You likely want to use `jupyter trust`... continue in 5 sec. Press Ctrl-C to quit now.
```

Each of those add 5 sec wait to the build time, which can amount to a lot in a repo containing a bunch of small notebooks.

**Comment by andrewosh** [comment]
Fixed in https://github.com/binder-project/binder-build-core/commit/6187f21f90fa842582305dcb725f516b72685245. Thanks!
