### ISSUE TITLE
Persistent files (that have been removed from the repo) between build

### ISSUE THREAD

**Issue by rougier** [binder-project/binder#71]
I've setub a binder on https://github.com/rougier/numpy-100 and between two builds, I've removed some files from my repo but they still appear in the binder.

Not critical at all though but I wonder how they end up in the docker file.

**Comment by andrewosh** [comment]
Fixed in https://github.com/binder-project/binder-build/commit/c8be8151a86790bde2b881a6331fe098739c8ba6. Thanks for opening the issue @rougier!
