### ISSUE TITLE
Recovering from Error: ENOSPC: no space left on device

### ISSUE THREAD

**Issue by psychemedia** [binder-project/binder#77]
Hi-

This revisits https://github.com/binder-project/binder/issues/74

I've been trying to pack a mybinder machine with libraries to demo a wide range of notebook embedding features and seem to have overloaded the VM when rebuilding via mybinder with a custom `Dockerfile`:

```
starting build for URL: https://github.com/psychemedia/ou-tm11n
fetching source at https://github.com/psychemedia/ou-tm11n
could not build image psychemedia-ou-tm11n: Error: ENOSPC: no space left on device, mkdir '/home/andrew/apps/psychemedia-ou-tm11n'
```

Is there a quick way to recover from this? The space seems to have run out to such an extent I can't even copy over a minimal setup (no `Dockerfile` etc).

Is there a way to force the freeing up of space to allow a (lighter) rebuild? (It would be a pain to have to mint a new repo; that said, I've learned my lesson and will do smaller builds for particular demos...)

Is there any memory allocation going on (eg for containers) that gets freed up when any running containers off that build are expired?

After 3-4 hours, the image would rebuild (I think after @freeman-lab cleaned up old images on the build machine?) but fails at the last step, again as described in https://github.com/binder-project/binder/issues/74 .

```
Removing intermediate container bd84f6129abd
Successfully built dee616b21525
could not build image psychemedia-ou-tm11n: Error: build failed for imageName: psychemedia-ou-tm11n
registering template for psychemedia-ou-tm11n
```

Are these delays tied in to regularly scheduled housekeeping jobs? If so, what schedule do they run to?

**Comment by freeman-lab** [comment]
This issue was resolved by cleaning up disk space.

**Comment by mfouesneau** [comment]
Same issue is back

**Comment by himito** [comment]
I have the same problem :(

**Comment by robinovitch61** [comment]
Same here
