### ISSUE TITLE
Widget Javascript not detected

### ISSUE THREAD

**Issue by aflaxman** [binder-project/binder#83]
Hi All, thanks for this amazing project / service.  I'm running into an issue with ipywidgets in mybinder in my project here http://mybinder.org/repo/aflaxman/iths-communicating-results-visually-2 .  This is the error:

```
Widget Javascript not detected.  It may not be installed properly. Did you enable the widgetsnbextension? If not, then run "jupyter nbextension enable --py --sys-prefix widgetsnbextension"
```

However, it seems that installing the packages and running this command does not solve the problem.  I tried executing the following cells in the notebook:

```
!conda install -y ipywidgets widgetsnbextension
!jupyter nbextension enable --py --sys-prefix widgetsnbextension
```

I believe I found a related issue here: https://github.com/SciTools/cube_browser/issues/100 , but I'm hoping for a simpler solution. Thanks again!

**Comment by aflaxman** [comment]
I used the Dockerfile approach from https://github.com/SciTools/cube_browser/issues/100 successfully, although I did something a little uncool with the pip packages, I think:  https://github.com/aflaxman/iths-communicating-results-visually-2/blob/master/Dockerfile

It is all working now, though.  Thanks again!

**Comment by SylvainCorlay** [comment]
@aflaxman checkout how we did this for the bqplot or pythreejs binder: `nodefault` and `conda-forge` channels.

**Comment by aflaxman** [comment]
would love to, is this the place to look? https://github.com/bloomberg/bqplot/blob/master/environment.yml
https://github.com/jovyan/pythreejs/blob/master/environment.yml

it looks simpler than my approach

**Comment by SylvainCorlay** [comment]
That is right. the issue is that the default channel's packages do some nasty things which override enabled extensions.

Disabling the default channel and relying only on conda-forge is a good fix until this is fixed.

**Comment by MInner** [comment]
I had to update `conda install -c conda-forge ipywidgets` and restart kernel to get rid of these warning messages.
