### ISSUE TITLE
Update the conda version in the base image

### ISSUE THREAD

**Issue by ocefpaf** [binder-project/binder#86]
I am trying to build a binder using the [this](https://github.com/ioos/notebooks_demos/blob/master/environment.yml#L2-L5) env file which is quite sensitive to the channel order. Binder builds just fine but I get the wrong version some of its dependencies (`icu`), and a broken env :unamused: 

When using the same env file locally I get the right versions, so I am guessing the issue is the `conda` version used in `binder`.

I am trying now to use the `Dockerfile` approach, and update `conda` before creating the env. See https://github.com/ocefpaf/notebooks_demos/blob/master/Dockerfile#L8 but that is returning:

```
# > source deactivate IOOS #
---> 70edd36d67f6
Removing intermediate container 941826cb2cef
Step 15 : RUN source activate IOOS
---> Running in e2274012c0a4
[91m/bin/sh: 1: source: not found[0m
could not build image ocefpaf-notebooks_demos: Error: build failed for imageName: ocefpaf-notebooks_demos
registering template for ocefpaf-notebooks_demos
```

See http://mybinder.org/status/ocefpaf/notebooks_demos

Any recommendations? Is a `conda` update possible? (So the channel preference feature is enabled.)

Can we take advantage of the channel preference feature? Or would that break binder dependencies?

cc @rsignell-usgs

**Comment by SylvainCorlay** [comment]
Hi, I have exactly the same issue (with the gdal package on conda-forge).

My understanding is that binder always downloads the latest miniconda, which should do the job.

I guess that redeploying would do the trick.

**Comment by ocefpaf** [comment]
BTW adding [this](https://github.com/ocefpaf/notebooks_demos/blob/master/Dockerfile#L12) line fixed it for me. So I am closing this.

**Comment by SylvainCorlay** [comment]
Well, this forces me to use docker instead of a pure conda....
