### ISSUE TITLE
After a long time waiting, it failed

### ISSUE THREAD

**Issue by qingkaikong** [binder-project/binder#88]
I had a repo built, and at first it all works well. But since 2 days ago, I can not get access to the repo, after launch, it keep showing 'Loading', until a big red fail shows up. I tried other binder examples, it seems I got the same results. Could you check this please?  Thanks!

My repo is:
http://mybinder.org/repo/qingkaikong/20161202_ann_basics

**Comment by qingkaikong** [comment]
It works now, so I am closing it.

**Comment by nealmcb** [comment]
I've been seeing something similar for a day now. At first it would just spin saying "loading" for a long time, perhaps hours.  Now it fails after one minute, saying "failed".  This is the first time I've tried binder, and I don't get any information about what is going wrong, or really know if the repo should work. The url is http://mybinder.org/repo/datadetectives/kaggle-titanic
