### ISSUE TITLE
Binder broken with Jupyter notebook version >= 4.3.0

### ISSUE THREAD

**Issue by jdemeyer** [binder-project/binder#94]
The token authentication which was enabled by default in notebook-4.3.0 breaks binder. See for example http://mybinder.org/repo/jdemeyer/icms-talk-20170118 which uses notebook version 4.3.1 (I need that because the notebook uses some new Jupyter features).

**Comment by mbeyeler** [comment]
+1

**Comment by minrk** [comment]
This has been fixed for a few months if you use `environment.yml` ([ref](https://github.com/binder-project/binder-build-core/pull/10)), and should be fixed [shortly](https://github.com/binder-project/binder-build-core/pull/16) for all images.
